services:
  taskRepository:
    class: pake\core\TaskRepository
  pakefileFactory:
    class: pake\core\CyclicResolutionPakefileFactory
  executionStrategyFactory:
    class: pake\core\ExecutionStrategyFactory
    arguments: [@taskRepository]
  taskExecutorFactory:
    class: pake\core\TaskExecutorFactory
    arguments: [@taskRepository, @executionStrategyFactory]
  application:
    class: pake\core\Application
    arguments: [@taskRepository, @pakefileFactory, @taskExecutorFactory]
  homePathProvider:
    class: pake\core\ServerHomePathProvider